### ISSUE TITLE
Can I start a container and skip the setup form

### ISSUE THREAD

**Issue by IanWhitney** [factorhouse/kpow#6]
**Version of Kpow**
CE 90.1

**Describe the issue**
I'm interested in starting up a container with my cluster config already defined in env vars. But doing so still takes me to the Setup form.

We have a cluster that uses SSL. I've set up a docker-compose file with the environment vars that should be enough for kpow to connect. I've provided the file below.

**Additional context**

Current Docker Compose file

```yml
version: '2.1'

services:
  kpow:
    image: factorhouse/kpow-ce
    ports:
      - "3000:3000"
    volumes:
      - /etc/pki/tls/private/kafka.server.truststore.jks:/truststore.jks
      - /etc/pki/tls/private/kafka.server.keystore.jks:/keystore.jks
    environment:
      ENVIRONMENT_NAME: staging
      CLUSTER_ID: staging
      BOOTSTRAP: hostname1:9093,hostname2:9093,hostname3:9093
      SECURITY_PROTOCOL: SSL
      SSL_KEY_PASSWORD: redacted
      SSL_KEYSTORE_LOCATION: /keystore.jks
      SSL_KEYSTORE_PASSWORD:  redacted
      SSL_KEYSTORE_TYPE: jks
      SSL_TRUSTSTORE_LOCATION: /truststore.jks
      SSL_TRUSTSTORE_PASSWORD: redacted
      SSL_TRUSTSTORE_TYPE: jks
```
